# Generated by Django 4.1.3 on 2022-11-16 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9547bfd8-c913-47a4-a5e1-e8df53c6fcaa')),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
