# Generated by Django 4.1.3 on 2022-11-16 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_post_uid_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4567f247-d54b-4ffb-be9e-17a76d0ce935')),
        ),
    ]
